### ISSUE TITLE
missing uv.lock listed package (zope-testbrowser) in nix.

### ISSUE THREAD

**Issue by TyberiusPrime** [adisbladis/uv2nix#11] opened 2024-09-12 10:04 UTC
I'm having an issue where a package is refered to in uv.lock, but then missing on the nix side:

```
       error: attribute 'zope-testbrowser' missing

       at /nix/store/73lvdl7shz5ii6vy8vgbiys1wbfvh4hs-source/lib/lock1.nix:115:96:

          114|                 (
          115|                   dep: filter (package: dep.version == null || dep.version == package.version) candidates.${dep.name}
             |                                                                                                ^
          116|                 )
```

wheel/sdist preference does not lead to a change.

See https://github.com/TyberiusPrime/20240912_uv2nix_zope2_failure for reproduction

**Comment by adisbladis** [comment] 2024-09-12 21:42
Caused by `resolution-markers` being incorrectly filtered. Fixed in 5a061cc90dad0e652f20b5196fc70549471a8cf3.

**Closed by adisbladis** 2024-09-12 21:42 UTC
